default_platform(:ios)

platform :ios do
  desc "Build IPA without signing"
  lane :ci_build do
    sh "xcodebuild -project GestorProyectosHG.xcodeproj -scheme GestorProyectosHG -sdk iphoneos -configuration Release clean build CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY='' DEVELOPMENT_TEAM=''"

    sh "mkdir -p build/ipa"
    sh "xcodebuild -exportArchive -archivePath build/GestorProyectosHG.xcarchive -exportPath build/ipa -exportOptionsPlist ExportOptions.plist || true"
  end
end
